import { describe, expect, it } from "vitest";

import {
  canonicalIdForSymbol,
  classifySymbol,
  parseDescriptors,
  parseSymbol,
  qualifiedNameFor,
} from "../src/code-graph/providers/scip/scip-symbol.js";

/**
 * XSPEC-333 R3 (SCIP PoC): id-normalization layer (OQ-2 from R1).
 *
 * Every symbol string below was decoded from this PoC's real
 * `test/fixtures/scip-poc/index.scip` (generated by `scip-dotnet` v0.2.14
 * against the `.cs` sources in that same directory) — not hand-written or
 * guessed. The expected canonical ids are the REAL ids tree-sitter's own
 * `extractProject`/`qualifyFunctions` produce for the same source (verified
 * separately, empirically, while building this PoC — see the R3 report for
 * the full cross-check). This file asserts the pure string-based
 * normalization rule (`scip-symbol.ts`'s module doc) agrees with those real
 * tree-sitter ids on every symbol this fixture project defines — the
 * cross-check `scip-ingest.ts`'s module doc says is this module's job,
 * since `scip-ingest.ts` itself does NOT use this file's output for the
 * actual graph merge (it uses row-containment against a live tree-sitter
 * parse instead, for reasons documented there).
 */
describe("parseDescriptors", () => {
  it("parses a namespace segment", () => {
    expect(parseDescriptors("Services/")).toEqual([{ kind: "namespace", name: "Services" }]);
  });

  it("parses a type segment", () => {
    expect(parseDescriptors("OrderService#")).toEqual([{ kind: "type", name: "OrderService" }]);
  });

  it("parses namespace + type + method (no overload)", () => {
    expect(parseDescriptors("Services/OrderService#Validate().")).toEqual([
      { kind: "namespace", name: "Services" },
      { kind: "type", name: "OrderService" },
      { kind: "method", name: "Validate", disambiguator: undefined },
    ]);
  });

  it("parses a method with an overload disambiguator", () => {
    expect(parseDescriptors("Services/Calculator#Add(+1).")).toEqual([
      { kind: "namespace", name: "Services" },
      { kind: "type", name: "Calculator" },
      { kind: "method", name: "Add", disambiguator: "+1" },
    ]);
  });

  it("parses a term (field/property) segment", () => {
    expect(parseDescriptors("Models/Order#Id.")).toEqual([
      { kind: "namespace", name: "Models" },
      { kind: "type", name: "Order" },
      { kind: "term", name: "Id" },
    ]);
  });

  it("parses a trailing parameter segment (terminal, no dot after)", () => {
    expect(parseDescriptors("Services/OrderService#Process().(order)")).toEqual([
      { kind: "namespace", name: "Services" },
      { kind: "type", name: "OrderService" },
      { kind: "method", name: "Process", disambiguator: undefined },
      { kind: "parameter", name: "order" },
    ]);
  });
});

describe("parseSymbol", () => {
  it("splits scheme/manager/package-name/package-version/descriptor", () => {
    const parsed = parseSymbol("scip-dotnet nuget . . Services/OrderService#Validate().");
    expect(parsed).not.toBeNull();
    expect(parsed?.scheme).toBe("scip-dotnet");
    expect(parsed?.manager).toBe("nuget");
    expect(parsed?.packageName).toBe(".");
    expect(parsed?.packageVersion).toBe(".");
    expect(parsed?.descriptors.map((d) => d.name)).toEqual(["Services", "OrderService", "Validate"]);
  });

  it("returns non-null with an empty descriptor list for exactly 4 tokens (bare package ref)", () => {
    expect(parseSymbol("scip-dotnet nuget . .")).toEqual({
      scheme: "scip-dotnet",
      manager: "nuget",
      packageName: ".",
      packageVersion: ".",
      descriptors: [],
    });
  });

  it("returns null for fewer than 4 whitespace-separated tokens", () => {
    expect(parseSymbol("only three tokens")).toBeNull();
    expect(parseSymbol("one")).toBeNull();
  });
});

describe("classifySymbol", () => {
  it("classifies a bare type symbol as class", () => {
    const parsed = parseSymbol("scip-dotnet nuget . . Services/OrderService#");
    expect(classifySymbol(parsed!)).toBe("class");
  });

  it("classifies a method symbol as function", () => {
    const parsed = parseSymbol("scip-dotnet nuget . . Services/OrderService#Validate().");
    expect(classifySymbol(parsed!)).toBe("function");
  });

  it("classifies a term (field) symbol as other", () => {
    const parsed = parseSymbol("scip-dotnet nuget . . Models/Order#Id.");
    expect(classifySymbol(parsed!)).toBe("other");
  });

  it("classifies a parameter symbol as other (not the method itself)", () => {
    const parsed = parseSymbol("scip-dotnet nuget . . Services/OrderService#Process().(order)");
    expect(classifySymbol(parsed!)).toBe("other");
  });

  it("classifies a namespace-only symbol as other", () => {
    const parsed = parseSymbol("scip-dotnet nuget . . Services/");
    expect(classifySymbol(parsed!)).toBe("other");
  });
});

describe("qualifiedNameFor", () => {
  it("drops the namespace segment, keeps Type.Method", () => {
    const parsed = parseSymbol("scip-dotnet nuget . . Services/OrderService#Validate().");
    expect(qualifiedNameFor(parsed!)).toBe("OrderService.Validate");
  });

  it("strips the overload disambiguator so both overloads collapse to the same qualified name", () => {
    const first = parseSymbol("scip-dotnet nuget . . Services/Calculator#Add().");
    const second = parseSymbol("scip-dotnet nuget . . Services/Calculator#Add(+1).");
    expect(qualifiedNameFor(first!)).toBe("Calculator.Add");
    expect(qualifiedNameFor(second!)).toBe("Calculator.Add");
    expect(qualifiedNameFor(first!)).toBe(qualifiedNameFor(second!));
  });

  it("returns null for a symbol with no type/method segment (namespace only)", () => {
    const parsed = parseSymbol("scip-dotnet nuget . . Services/");
    expect(qualifiedNameFor(parsed!)).toBeNull();
  });
});

/**
 * Ground truth: the REAL ids `extractProject`/`qualifyFunctions` produced for
 * this exact fixture project (captured empirically while building this PoC —
 * see R3 report). This is the cross-check invariant the review of this PoC's
 * plan demanded: does the independently-derived string-parsing normalization
 * actually agree with tree-sitter's own id for the same real-world symbol?
 */
describe("canonicalIdForSymbol agrees with tree-sitter's real ids (cross-check)", () => {
  const cases: Array<{ symbol: string; definingFile: string; expected: { kind: "function" | "class"; id: string } }> = [
    {
      symbol: "scip-dotnet nuget . . Services/OrderService#Validate().",
      definingFile: "Services/OrderService.cs",
      expected: { kind: "function", id: "Services/OrderService.cs#OrderService.Validate" },
    },
    {
      symbol: "scip-dotnet nuget . . Services/OrderService#Process().",
      definingFile: "Services/OrderService.cs",
      expected: { kind: "function", id: "Services/OrderService.cs#OrderService.Process" },
    },
    {
      symbol: "scip-dotnet nuget . . Services/UserService#Validate().",
      definingFile: "Services/UserService.cs",
      expected: { kind: "function", id: "Services/UserService.cs#UserService.Validate" },
    },
    {
      symbol: "scip-dotnet nuget . . Services/UserService#Register().",
      definingFile: "Services/UserService.cs",
      expected: { kind: "function", id: "Services/UserService.cs#UserService.Register" },
    },
    {
      symbol: "scip-dotnet nuget . . Services/NotificationService#Notify().",
      definingFile: "Services/NotificationService.cs",
      expected: { kind: "function", id: "Services/NotificationService.cs#NotificationService.Notify" },
    },
    {
      symbol: "scip-dotnet nuget . . ScipPocSample/Program#Main().",
      definingFile: "Program.cs",
      expected: { kind: "function", id: "Program.cs#Program.Main" },
    },
    // Both overloads must collapse onto tree-sitter's single collapsed id —
    // matching its documented same-scope-overload limitation, not diverging
    // from it.
    {
      symbol: "scip-dotnet nuget . . Services/Calculator#Add().",
      definingFile: "Services/Calculator.cs",
      expected: { kind: "function", id: "Services/Calculator.cs#Calculator.Add" },
    },
    {
      symbol: "scip-dotnet nuget . . Services/Calculator#Add(+1).",
      definingFile: "Services/Calculator.cs",
      expected: { kind: "function", id: "Services/Calculator.cs#Calculator.Add" },
    },
    {
      symbol: "scip-dotnet nuget . . Services/OrderService#",
      definingFile: "Services/OrderService.cs",
      expected: { kind: "class", id: "Services/OrderService.cs#class:OrderService" },
    },
    {
      symbol: "scip-dotnet nuget . . Services/UserService#",
      definingFile: "Services/UserService.cs",
      expected: { kind: "class", id: "Services/UserService.cs#class:UserService" },
    },
    {
      symbol: "scip-dotnet nuget . . Models/Order#",
      definingFile: "Models/Order.cs",
      expected: { kind: "class", id: "Models/Order.cs#class:Order" },
    },
    {
      symbol: "scip-dotnet nuget . . ScipPocSample/Program#",
      definingFile: "Program.cs",
      expected: { kind: "class", id: "Program.cs#class:Program" },
    },
  ];

  for (const { symbol, definingFile, expected } of cases) {
    it(`"${symbol}" -> ${expected.id}`, () => {
      expect(canonicalIdForSymbol(symbol, definingFile)).toEqual(expected);
    });
  }

  it("returns null for non-function/class symbols (field, parameter, namespace)", () => {
    expect(canonicalIdForSymbol("scip-dotnet nuget . . Models/Order#Id.", "Models/Order.cs")).toBeNull();
    expect(
      canonicalIdForSymbol("scip-dotnet nuget . . Services/OrderService#Process().(order)", "Services/OrderService.cs"),
    ).toBeNull();
    expect(canonicalIdForSymbol("scip-dotnet nuget . . Services/", "Services/OrderService.cs")).toBeNull();
  });
});
