/**
 * Loader for the XSPEC-333 R3 (SCIP PoC) fixture project.
 *
 * `index.scip` was generated once, offline, via:
 *
 *   dotnet tool install --global scip-dotnet
 *   dotnet build ScipPocSample.csproj
 *   scip-dotnet index ScipPocSample.csproj --output index.scip
 *
 * against the `.cs` files in this directory (plus a `.csproj`/`bin`/`obj`
 * that are NOT committed — only the source + the generated binary index
 * are). Committing the generated `.scip` binary (rather than regenerating it
 * at test time) is deliberate: it keeps `npm test` independent of a `dotnet`/
 * `scip-dotnet` toolchain being present in CI or on any given contributor's
 * machine — this PoC's environment-viability finding was that this toolchain
 * IS available in the sandbox it was built in, but that is not something the
 * rest of this repo's test suite should have to assume going forward.
 *
 * If the sample project's `.cs` sources ever change, `index.scip` must be
 * regenerated by hand using the steps above and re-committed — there is no
 * automated check that the two are in sync (an accepted PoC-scope limitation,
 * not a production pattern).
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { readScipIndex, type ScipIndex } from "../../../src/code-graph/providers/scip/scip-reader.js";
import type { ScipSourceFile } from "../../../src/code-graph/providers/scip/scip-ingest.js";

const FIXTURE_DIR = dirname(fileURLToPath(import.meta.url));

/** Repo-relative (to the fixture project root) paths of every source file, matching `Document.relativePath` in `index.scip`. */
export const SCIP_POC_SOURCE_PATHS = [
  "Program.cs",
  "Models/Order.cs",
  "Models/User.cs",
  "Services/OrderService.cs",
  "Services/UserService.cs",
  "Services/NotificationService.cs",
  "Services/Calculator.cs",
] as const;

export function loadScipPocFixtureSources(): ScipSourceFile[] {
  return SCIP_POC_SOURCE_PATHS.map((relativePath) => ({
    relativePath,
    source: readFileSync(join(FIXTURE_DIR, relativePath), "utf8"),
  }));
}

export function loadScipPocFixtureIndex(): ScipIndex {
  return readScipIndex(join(FIXTURE_DIR, "index.scip"));
}
