/**
 * Loader for the XSPEC-333 R3 Java PoC fixture project — the second
 * SCIP-backed language, added to check whether the C# PoC's ingest design
 * (`scip-ingest.ts`) actually generalizes, or only happened to work for one
 * language/indexer-version pairing. See `test/scip-java-ingest.test.ts`'s
 * module doc for what this extension found.
 *
 * `index.scip` was generated once, offline, via:
 *
 *   # JDK 17+ required; coursier bootstraps scip-java from Maven Central.
 *   curl -fLo coursier https://git.io/coursier-cli && chmod +x coursier
 *   ./coursier launch org.scip-code:scip-java:0.13.1 \
 *     --main-class org.scip_code.scip_java.ScipJava -- index
 *
 * against the `.java` files in this directory (plus a `pom.xml`/`target` that
 * IS committed for `pom.xml` but NOT for `target` — only source + the
 * generated binary index are committed, same policy as the C# PoC fixture).
 *
 * If the sample project's `.java` sources ever change, `index.scip` must be
 * regenerated by hand using the steps above and re-committed — there is no
 * automated check that the two are in sync (same accepted PoC-scope
 * limitation as the C# fixture, not a production pattern).
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { readScipIndex, type ScipIndex } from "../../../src/code-graph/providers/scip/scip-reader.js";
import type { ScipSourceFile } from "../../../src/code-graph/providers/scip/scip-ingest.js";

const FIXTURE_DIR = dirname(fileURLToPath(import.meta.url));

/** Repo-relative (to the fixture project root) paths of every source file, matching `Document.relativePath` in `index.scip`. */
export const SCIP_JAVA_POC_SOURCE_PATHS = [
  "src/main/java/com/example/Program.java",
  "src/main/java/com/example/models/Order.java",
  "src/main/java/com/example/models/User.java",
  "src/main/java/com/example/services/OrderService.java",
  "src/main/java/com/example/services/UserService.java",
  "src/main/java/com/example/services/NotificationService.java",
  "src/main/java/com/example/services/Calculator.java",
] as const;

export function loadScipJavaPocFixtureSources(): ScipSourceFile[] {
  return SCIP_JAVA_POC_SOURCE_PATHS.map((relativePath) => ({
    relativePath,
    source: readFileSync(join(FIXTURE_DIR, relativePath), "utf8"),
    language: "java" as const,
  }));
}

export function loadScipJavaPocFixtureIndex(): ScipIndex {
  return readScipIndex(join(FIXTURE_DIR, "index.scip"));
}
