/**
 * Loader for the XSPEC-333 R3 Java PoC fixture project — the second
 * SCIP-backed language, added to check whether the C# PoC's ingest design
 * (`scip-ingest.ts`) actually generalizes, or only happened to work for one
 * language/indexer-version pairing. See `test/scip-java-ingest.test.ts`'s
 * module doc for what this extension found.
 *
 * ## How `index.scip` was generated (accurate, tested recipe)
 *
 * Corrected by adversarial review of an earlier draft of this comment, which
 * omitted two real, load-bearing prerequisites below (Maven itself, and a
 * working `bash`) and overstated what the `coursier launch` step alone
 * needed. This recipe is what was ACTUALLY run, in order, in a from-scratch
 * environment with none of JDK/Maven/coursier pre-installed:
 *
 *   1. **JDK 17+ on PATH** (Eclipse Temurin 17.0.19 was used; any JDK 17+
 *      works per `scip-java`'s own docs — no `--add-exports` flags need to
 *      be supplied BY YOU: `scip-java index`'s generated Maven invocation
 *      already injects the JVM options its own docs mention into the forked
 *      javac process itself, via its `custom-javac.sh` wrapper — see point 4).
 *   2. **Apache Maven on PATH** (3.9.16 was used) — `scip-java index`'s
 *      default command literally shells out to `mvn`; it does not vendor or
 *      replace Maven itself.
 *   3. **A `bash` on PATH that is >= 4.4** (NOT this fixture's `pom.xml` —
 *      an earlier draft of this file's sibling `pom.xml` wrongly tried to
 *      route around the issue below via `maven.compiler.meminitial`/
 *      `maxmem` properties; that did NOT work and has been removed).
 *      `scip-java`'s generated `custom-javac.sh` wrapper does
 *      `javac ... "${LAUNCHER_ARGS[@]}"` under `set -eu`; when no `-J`
 *      prefixed args are present `LAUNCHER_ARGS` stays a declared-but-empty
 *      array, and expanding an EMPTY array with `${arr[@]}` under `set -u`
 *      throws "unbound variable" on any bash older than 4.4 — including
 *      macOS's stock `/bin/bash` (3.2.57, GPL-frozen; Apple ships no newer
 *      bash). This crashes even Maven's own internal, unconfigurable
 *      `javac -version` probe, so it cannot be worked around via any
 *      compiler-plugin property — it must be fixed by putting a real bash
 *      >= 4.4 ahead of `/bin`/`/usr/bin` on `PATH` (so `#!/usr/bin/env bash`
 *      resolves to it). On macOS with no admin/brew write access, building
 *      GNU bash from source (`clang`/`cc` is normally already present) into
 *      a scratch prefix works:
 *        curl -fLo bash.tar.gz https://ftp.gnu.org/gnu/bash/bash-5.2.37.tar.gz
 *        tar xzf bash.tar.gz && cd bash-5.2.37
 *        ./configure --prefix=/some/scratch/dir && make
 *        # then prepend /some/scratch/dir/bash's build output dir to PATH
 *   4. **Bootstrap and run `scip-java` 0.13.1 via coursier**:
 *        curl -fLo coursier https://git.io/coursier-cli && chmod +x coursier
 *        ./coursier launch org.scip-code:scip-java:0.13.1 \
 *          --main-class org.scip_code.scip_java.ScipJava -- index
 *      run from this directory (containing `pom.xml`) — produces
 *      `index.scip` alongside it.
 *
 * (plus a `target/` build directory that is NOT committed — only the
 * `.java` sources, `pom.xml`, and the generated binary `index.scip` are,
 * same policy as the C# PoC fixture.)
 *
 * If the sample project's `.java` sources ever change, `index.scip` must be
 * regenerated by hand using the steps above and re-committed — there is no
 * automated check that the two are in sync (same accepted PoC-scope
 * limitation as the C# fixture, not a production pattern).
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { readScipIndex, type ScipIndex } from "../../../src/code-graph/providers/scip/scip-reader.js";
import type { ScipSourceFile } from "../../../src/code-graph/providers/scip/scip-ingest.js";

const FIXTURE_DIR = dirname(fileURLToPath(import.meta.url));

/** Repo-relative (to the fixture project root) paths of every source file, matching `Document.relativePath` in `index.scip`. */
export const SCIP_JAVA_POC_SOURCE_PATHS = [
  "src/main/java/com/example/Program.java",
  "src/main/java/com/example/models/Order.java",
  "src/main/java/com/example/models/User.java",
  "src/main/java/com/example/services/OrderService.java",
  "src/main/java/com/example/services/UserService.java",
  "src/main/java/com/example/services/NotificationService.java",
  "src/main/java/com/example/services/Calculator.java",
] as const;

export function loadScipJavaPocFixtureSources(): ScipSourceFile[] {
  return SCIP_JAVA_POC_SOURCE_PATHS.map((relativePath) => ({
    relativePath,
    source: readFileSync(join(FIXTURE_DIR, relativePath), "utf8"),
    language: "java" as const,
  }));
}

export function loadScipJavaPocFixtureIndex(): ScipIndex {
  return readScipIndex(join(FIXTURE_DIR, "index.scip"));
}
